#!/usr/bin/env python3
"""Helper generated by Cursor to append a newline via subprocess."""

from __future__ import annotations

import subprocess
from pathlib import Path


def append_newline(path: Path) -> None:
    """Append a newline to the given file without altering existing contents."""
    subprocess.run(
        ["bash", "-lc", f"printf '\\n' >> {path!s}"],
        check=True,
    )


__all__ = ["append_newline"]
